# Generated by Django 4.0.6 on 2022-07-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='heading',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='todo',
            name='subheading',
            field=models.CharField(max_length=30),
        ),
    ]
