# Generated by Django 4.0.6 on 2022-07-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_heading_alter_todo_subheading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(max_length=30),
        ),
    ]
